set nocompatible
set ru
set nu
set hls
"set cul     " set cursorline

" 这两句只在 Linux 下需要
" so $VIMRUNTIME/delmenu.vim
" so $VIMRUNTIME/menu.vim
" 选用配色方案
colorscheme desert

    " Platform
function! MySys()
    return "windows"
    endfunction

    " This line should not be removed as it ensures that various options are
    " properly set to work with the Vim-related packages available in Debian.
    " runtime! debian.vim

    " Uncomment the next line to make Vim more Vi-compatible
    " NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
    " options, so any other options should be set AFTER setting 'compatible'.
    " set compatible

    " Vim5 and later versions support syntax highlighting. Uncommenting the next
    " line enables syntax highlighting by default.
    syntax on

    set bdir=~/tmp

    "highlight Search ctermbg=LightGreen cterm=underline
    highlight Search term=standout ctermfg=0 ctermbg=3

    " Uncomment the following to have Vim jump to the last position when
    " reopening a file
    " if has("autocmd")
    "  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    "              \| exe "normal g'\"" | endif
    " endif

    " Uncomment the following to have Vim load indentation rules according to the
    " detected filetype. Per default Debian Vim only load filetype specific
    " plugins.
    if has("autocmd")
    filetype indent on
    endif

    " The following are commented out as they cause vim to behave a lot
    " differently from regular Vi. They are highly recommended though.
    set showcmd     " Show (partial) command in status line.
    set showmatch       " Show matching brackets.
    "set ignorecase     " Do case insensitive matching
    set smartcase       " Do smart case matching
    "set incsearch      " Incremental search
    set autowrite       " Automatically save before commands like :next and :make
    "set hidden             " Hide buffers when they are abandoned

    "set mouse=a        " Enable mouse usage (all modes) in terminals
    set mousemodel=popup
    set shiftwidth=4
    set tabstop=4
    set expandtab
    set softtabstop=4
    set pastetoggle=<F7>
    set autoindent
    autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
    set backspace=indent,eol,start
    set whichwrap=b,s,,[,]
    set et
    set lbr
    set fo+=mB
    set sm
    set cin
    set cino=:0g0t0(sus
    set ai

    " 
    " 默认是  "menu,preview"
    " 更多查看 help completeopt
    " set completeopt=longest,menu

    " let g:calendar_diary="F:\\My\ Documents\\我的备份\\diary"
    map <C-J> <C-W>j
    map <C-K> <C-W>k

    " 这项必须设定，否则出错,配置taglist的ctags路径
    filetype on
   " add by xjzhou 2008.12.13
function AddFileDesc()
    if &syntax=="cpp" || &syntax=="c" || &syntax=="h" || &syntax=="java"
        call setline(1,"/*******************************************************************")    
        call  append(1,"* Copyright (c) www.shujuzhou.com")
        call  append(2,"* File: ".expand("%"))
        call  append(3,"* Author: xjzhou@shujuzhou.com)")
        call  append(4,"* Date Created: ".strftime("%m/%d/%Y %H:%M"))
        call  append(5,"* Date Revised: ".strftime("%m/%d/%Y %H:%M"))
        call  append(6,"* Desc: ")
        call  append(7,"* Usage: ")
        call  append(8,"********************************************************************/")
    elseif &syntax=="sh" || &syntax=="awk" || &syntax=="py"
        if &syntax=="sh"
             call setline(1,"#!/bin/bash")
        elseif &syntax=="awk"
            call setline(1,"#!/usr/bin/awk -f")
        elseif &syntax=="py"
            call setline(1,"#!/usr/bin/env python")
        endif
        call append(1,"")
        call append(2,"####################################################################")
        call append(3,"# Copyright (c) www.shujuzhou.com")
        call append(4,"# File: ".expand("%"))
        call append(5,"# Author: xjzhou@shujuzhou.com)
        call append(6,"# Date Created: ".strftime("%m/%d/%Y %H:%M"))
        call append(7,"# Date Revised: ".strftime("%m/%d/%Y %H:%M"))
        call append(8,"# Desc: ")
        call append(9,"# Usage: ")
        call append(10,"####################################################################")
    else
        call append(0,"####################################################################")
        call append(1,"# Copyright (c) www.shujuzhou.com")
        call append(2,"# Author: xjzhou@shujuzhou.com")
        call append(3,"# Date Created: ".strftime("%m/%d/%Y %H:%M"))
        call append(4,"# Date Revised: ".strftime("%m/%d/%Y %H:%M"))
        call append(5,"# Desc: ")
        call append(6,"# Usage: ")
        call append(7,"####################################################################")
        endif
    endf
    map <F5> :call AddFileDesc()<cr><ESC>Go

    function AddTest()
    endf

    "map <F6> :/ \* *Last modified:/s@.*@\=strftime("%Y-%m-%d %H:%M")@<cr>

    map <F1> :MRU <CR>

    " 根据文件格式加注释
function AddRemark()
    if &syntax=="cpp" || &syntax=="c" || &syntax=="h" || &syntax=="php"
    execute "normal  \<ESC>\<S-$>a// by xjzhou".strftime("%m/%d/%Y")"\<ESC>27hi"
    elseif &syntax=="awk" || &syntax=="sh"
    execute "normal \<ESC>\<S-$>a# by xjzhou" .strftime("%m/%d/%Y")"\<ESC>26hi"
    endif
    endf

    map <F6> <Esc>:call AddRemark()<CR><Esc>

    " latex 的设置
    " REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
    filetype plugin on

    " IMPORTANT: win32 users will need to have 'shellslash' set so that latex
    " can be called correctly.
    set shellslash

    " IMPORTANT: grep will sometimes skip displaying the file name if you
    " search in a singe file. This will confuse Latex-Suite. Set your grep
    " program to always generate a file-name.
    set grepprg=grep\ -nH\ $*

    " OPTIONAL: This enables automatic indentation as you type.
    filetype indent on

    " OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
    " 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
    " The following changes the default filetype back to 'tex':
    let g:tex_flavor='latex'

    command! -bar -nargs=0 SudoW   :silent exe "write !sudo tee % >/dev/null"|silent edit!

    " VIM 记住上次编辑位置的方法
    autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \ exe "normal g`\"" |
    \ endif

" 插入模式切换
map <F7> :set paste!<BAr>set paste?<CR>
"
" 多 Tab 时翻页
map <silent> <F8> :tabprevious<CR>
imap <silent> <F8> <Esc>:tabprevious<CR>gi

map <silent> <F9> :tabnext<CR>
imap <silent> <F9> <Esc>:tabnext<CR>gi

"pydiction 1.2 python auto complete
filetype plugin on
let g:pydiction_location = '~/.vim/tools/pydiction/complete-dict'
"defalut g:pydiction_menu_height == 15
"let g:pydiction_menu_height = 20 
"
""""""""""""""""""""""""""""""
" Tag list (ctags)
""""""""""""""""""""""""""""""
if MySys() == "windows"                "设定windows系统中ctags程序的位置
    let Tlist_Ctags_Cmd = 'ctags'
else  
    let Tlist_Ctags_Cmd = '/usr/local/bin/ctags' 
endif

let Tlist_Show_One_File = 1            "不同时显示多个文件的tag，只显示当前文件的
let Tlist_Exit_OnlyWindow = 1          "如果taglist窗口是最后一个窗口，则退出vim
let Tlist_Use_Right_Window = 0         "在右侧窗口中显示taglist窗口

"""""""""""""""""""""""""""""""
"" winManager setting
"""""""""""""""""""""""""""""""
"设置界面分割
"let g:winManagerWindowLayout='NERDTree|TagList,BufExplorer'
let g:winManagerWindowLayout='FileExplore|TagList,BufExplorer'

"设置winmanager的宽度，默认为25
let g:winManagerWidth = 30

"在进入vim时自动打开winmanager
let g:AutoOpenWinManager = 0
if g:AutoOpenWinManager 
    "autocmd VimEnter * nested call s:StartWindowsManager()|1wincmd w  
    autocmd VimEnter * nested call s:StartWindowsManager()|1wincmd w|q
endif

let g:NERDTree_title="[NERDTree]" 

function! NERDTree_Start()
    exec 'NERDTree'
endfunction

function! NERDTree_IsValid()
    return 1
endfunction

"定义打开关闭winmanager按键
nmap wm :if IsWinManagerVisible() <BAR> WMToggle<CR> <BAR> else <BAR> WMToggle<CR>:q<CR> endif <CR><CR>
nmap <F3> :if IsWinManagerVisible() <BAR> WMToggle<CR> <BAR> else <BAR> WMToggle<CR>:q<CR> endif <CR><CR>

"vim-pathogen
execute pathogen#infect()

"git commit msg
autocmd Filetype gitcommit setlocal spell textwidth=72
